services:
  # MySQL Database
  mysql:
    build: ./mysql
    container_name: doriav2-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: doriav2_root_password
      MYSQL_DATABASE: doriav2
      MYSQL_USER: doriav2_user
      MYSQL_PASSWORD: doriav2_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
    networks:
      - doriav2_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdoriav2_root_password"]
      timeout: 10s
      retries: 3
      interval: 30s

  # Redis Cache (for sessions and caching)
  redis:
    image: redis:7-alpine
    container_name: doriav2-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - doriav2_network
    command: redis-server --appendonly yes --requirepass doriav2_redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "doriav2_redis_password", "ping"]
      timeout: 5s
      retries: 3
      interval: 30s

  # PHP/Apache Web Server (placeholder for future app)
  web:
    image: php:8.2-apache
    container_name: doriav2-web
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_NAME=doriav2
      - DB_USER=doriav2_user
      - DB_PASSWORD=doriav2_password
      - REDIS_HOST=redis
      - REDIS_PASSWORD=doriav2_redis_password
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - web_logs:/var/log/apache2
    networks:
      - doriav2_network
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git &&
      docker-php-ext-configure gd --with-freetype --with-jpeg &&
      docker-php-ext-install gd pdo pdo_mysql mysqli &&
      a2enmod rewrite headers &&
      echo '<Directory /var/www/html>' >> /etc/apache2/apache2.conf &&
      echo '  AllowOverride All' >> /etc/apache2/apache2.conf &&
      echo '</Directory>' >> /etc/apache2/apache2.conf &&
      echo '<?php phpinfo(); ?>' > /var/www/html/index.php &&
      apache2-foreground
      "

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: doriav2-phpmyadmin
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: doriav2_user
      PMA_PASSWORD: doriav2_password
      MYSQL_ROOT_PASSWORD: doriav2_root_password
    ports:
      - "8081:80"
    networks:
      - doriav2_network

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: doriav2-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP
    networks:
      - doriav2_network

  # Asterisk PBX Server
  asterisk:
    build: ./asterisk
    container_name: doriav2-asterisk
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_NAME=doriav2
      - DB_USER=doriav2_user
      - DB_PASSWORD=doriav2_password
    ports:
      - "5060:5060/udp"  # SIP UDP
      - "5060:5060/tcp"  # SIP TCP
      - "5038:5038"      # AMI (Asterisk Manager Interface)
      - "10000-10100:10000-10100/udp"  # RTP range
    volumes:
      - asterisk_etc:/etc/asterisk
      - asterisk_lib:/var/lib/asterisk
      - asterisk_log:/var/log/asterisk
      - asterisk_spool:/var/spool/asterisk
    networks:
      - doriav2_network
    healthcheck:
      test: ["CMD", "pgrep", "asterisk"]
      timeout: 10s
      retries: 5
      interval: 15s

  # FreePBX Web Interface
  freepbx:
    build: ./freepbx
    container_name: doriav2-freepbx
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      asterisk:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_NAME=doriav2
      - DB_USER=doriav2_user
      - DB_PASSWORD=doriav2_password
      - ASTERISK_HOST=asterisk
    ports:
      - "8082:80"  # FreePBX Web Interface
    volumes:
      - freepbx_data:/var/www/html/freepbx
      - freepbx_logs:/var/log/apache2
    networks:
      - doriav2_network

networks:
  doriav2_network:
    driver: bridge
    name: doriav2_network

volumes:
  mysql_data:
    name: doriav2_mysql_data
  mysql_logs:
    name: doriav2_mysql_logs
  redis_data:
    name: doriav2_redis_data
  web_logs:
    name: doriav2_web_logs
  asterisk_etc:
    name: doriav2_asterisk_etc
  asterisk_lib:
    name: doriav2_asterisk_lib
  asterisk_log:
    name: doriav2_asterisk_log
  asterisk_spool:
    name: doriav2_asterisk_spool
  freepbx_data:
    name: doriav2_freepbx_data
  freepbx_logs:
    name: doriav2_freepbx_logs