version: '3.8'

services:
  svi-angular:
    build:
      context: ./frontend/angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/angular/src:/app/src
      - ./frontend/angular/angular.json:/app/angular.json
      - ./frontend/angular/tsconfig.json:/app/tsconfig.json
    environment:
      - NODE_ENV=development
    container_name: svi-flow-editor
    restart: unless-stopped
    networks:
      - doriav2_network

networks:
  doriav2_network:
    external: true
